name: Deploy Java project to Azure Function App

on:
  push:
    branches: ["main"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # غيّرها لاسم Function App عندك على Azure
  POM_XML_DIRECTORY: 'LostAndFound'         # المجلد اللي فيه pom.xml (عدله حسب مكانك الفعلي)
  DISTRIBUTION: 'zulu'                      # نسخة JDK
  JAVA_VERSION: '8'                         # إصدار جافا

jobs:
  build-and-deploy:
    runs-on: windows-latest # أو ubuntu-latest لو تفضل لينكس
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: 'Build with Maven'
      shell: pwsh
      run: |
        cd ${{ env.POM_XML_DIRECTORY }}
        mvn clean package

    - name: 'Deploy to Azure Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.AZURE_FUNCTIONAPP_NAME }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-pom-xml: true
