name: Full DevOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  JAVA_VERSION: 8
  DISTRIBUTION: zulu
  POM_XML_DIRECTORY: 'LostAndFound'       
  AZURE_FUNCTIONAPP_BETA: 'com-ucas-lostandfound-beta'
  AZURE_FUNCTIONAPP_PROD: 'com-ucas-lostandfound'

permissions:
  contents: read
  security-events: write  

jobs:
  # ===== Build =====
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build project
        run: mvn clean package
        working-directory: ${{ env.POM_XML_DIRECTORY }}

  # ===== Test =====
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Run Tests
        run: mvn test
        working-directory: ${{ env.POM_XML_DIRECTORY }}

  # ===== Package =====
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Package Project
        run: mvn package
        working-directory: ${{ env.POM_XML_DIRECTORY }}

  # ===== Deploy Beta =====
  deploy-beta:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Deploy to Azure Function (Beta)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_BETA }}
          package: '${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.AZURE_FUNCTIONAPP_BETA }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_BETA }}
          respect-pom-xml: true

  # ===== Deploy Production =====
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-beta
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Deploy to Azure Function (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_PROD }}
          package: '${{ env.POM_XML_DIRECTORY }}/target/azure-functions/${{ env.AZURE_FUNCTIONAPP_PROD }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD }}
          respect-pom-xml: true
